# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20160922_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
