# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20160922_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('articles', models.ManyToManyField(to='article.Article')),
            ],
        ),
    ]
